### ISSUE TITLE
[Bug] “Hide Shorts Cells” does not remove the Shorts cells from the homepage.

### ISSUE THREAD

**Issue by ThanhPhuoc91** [arichorn/uYouPlus-Downloads#11]
Steps to reproduce the issue:
1.Enable “Hide Shorts Cells” in uYou’s “Home” settings.
2.Restart the app.
3.The Shorts Cells are still in the homepage.

**Comment by arichornlover** [comment]
Whenever I update this repository. There will be a new option `Hide Shorts Cells`  which will appear in `Settings > uYouPlus > Miscellaneous`
